version: '3.8'

services:
  n2d:
    build:
      context: ./notion2discord
      args:
        MINUTES: "15"
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
      - n2d_dir:/usr/src/app

volumes:
  n2d_dir: