# Grab Python image
FROM python:3.9-slim

# Accept the number of minutes as a build argument
ARG MINUTES=1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install cron
RUN apt-get update && apt-get -y install cron

# Create crontab file and set up cron job
RUN echo "*/${MINUTES} * * * * cd /usr/src/app && /usr/local/bin/python -B main.py >> /var/log/n2d.log 2>&1" > /etc/cron.d/n2d-crontab

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/n2d-crontab

# Apply cron job
RUN crontab /etc/cron.d/n2d-crontab

# Create the log file to be able to run tail
RUN touch /var/log/n2d.log

# Run the command on container startup
CMD cron && tail -f /var/log/n2d.log